/* =====================================================================
   STILL BREATHING — storyData.js
   ALL game content. Engine-agnostic data.
   node: { region, title, text(str|fn), enter?(S,P), choices:[
            t(str|fn), pre?, req?(S,P), item?:'kitId', find?:'kitId', myth?,
            grip?/warmth?/water?/food?/body? (deltas), rescue?, day?, log?:'id',
            fx?(S,P), go?(str|fn), end?(str|fn), noDeath? ] }
   Three ordeals, each grounded in a real survival case. Text may hold HTML;
   {NAME} = player. Speech / thought uses <em>. Cold hallucination: .whisper
   ===================================================================== */
const STORY = (() => {

/* ---------------- scenarios ---------------- */
const scenarios = {
  white: { name:'The White Mile', tag:'bush plane · subarctic', art:'crash', start:'w_wake', goal:4,
    vitals:{grip:4,warmth:3,water:5,food:4,body:3},
    desc:'Your float plane is down in the backcountry, the pilot is dead, and the cold is coming. The wreck is your best chance — if you can keep from doing the reasonable-seeming thing.' },
  raft: { name:'The Raft', tag:'open ocean · adrift', art:'raft', start:'r_sink', goal:4,
    vitals:{grip:4,warmth:4,water:3,food:4,body:4},
    desc:'A whale holed your boat in the night. Now it is a six-foot raft, the whole Atlantic, and a sun that wants your water. Everything you know about drinking is a lie out here.' },
  pinch: { name:'The Pinch', tag:'slot canyon · pinned', art:'slot', start:'p_shift', goal:3,
    vitals:{grip:4,warmth:4,water:2,food:3,body:3}, kit:['multitool'],
    desc:'A boulder shifted and took your arm to the wall. You have a multitool, a mouthful of water, and no one on earth who knows where you went. There is one door out, and you will hate it.' },
  trail: { name:'The Trailhead', tag:'national park · off-trail', art:'trailday', start:'t_step', goal:4,
    vitals:{grip:4,warmth:4,water:3,food:3,body:4}, kit:['phone','whistle','tarp'],
    desc:'A marked trail, a clear morning, a thirty-second detour. You are never more than a few miles from the path — and people die exactly here, of embarrassment, bad certainty, and rain that isn’t even cold enough to fear.' },
};

/* ---------------- regions (label; art & audio share the key) ---------------- */
const regions = {
  crash:{name:'The Wreck'}, forest:{name:'The Timber'}, river:{name:'The River'},
  ridge:{name:'The Ridge'}, night:{name:'The First Night'}, camp:{name:'The Camp'},
  sinking:{name:'The Sinking'}, raft:{name:'The Raft'}, raftnight:{name:'The Raft — Night'},
  open:{name:'The Open Ocean'}, storm:{name:'The Squall'},
  slot:{name:'The Slot'}, slotday:{name:'The Slot — Noon'}, slotnight:{name:'The Slot — Night'},
  canyonout:{name:'The Way Down'}, rim:{name:'The Rim'},
  trailday:{name:'The Trail'}, offtrail:{name:'Off the Trail'}, creekbed:{name:'The Drainage'},
  stormnight:{name:'The Rain'}, ridgeview:{name:'The Dome'}, meadow:{name:'The Clearing'},
};

/* ---------------- kit ---------------- */
const items = {
  firekit:{ name:'fire kit',  desc:'the pilot’s lighter and a ferro rod. dry, so far.' },
  blade:{   name:'knife',      desc:'a folding blade. the most useful thing you own.' },
  sheet:{   name:'space blanket', desc:'mylar from the survival kit — insulation and a signal both.' },
  mirror:{  name:'signal mirror', desc:'polished cowling. a flash carries for miles.' },
  ditchkit:{name:'ditch bag',  desc:'water tins, flares, a solar still, a fishing kit. your whole life, in a bag.' },
  gaff:{    name:'gaff',        desc:'a spear made from an oar and a knife. the sea has food if you can hold on.' },
  still:{   name:'solar still', desc:'a bag that turns sun and seawater into a few sips of fresh.' },
  multitool:{name:'multitool', desc:'a cheap folding multitool. a dull two-inch blade. it will have to be enough.' },
  phone:{   name:'phone (dying)', desc:'forty percent battery and falling. every glance at it costs you a little of your last rope to the world.' },
  whistle:{ name:'whistle',    desc:'three short blasts, over and over. a whistle carries a mile farther than a voice and never goes hoarse.' },
  tarp:{    name:'signal tarp', desc:'a bright orange emergency tarp. shelter, or a signal the sky can read — if you choose to be seen.' },
  bandana:{ name:'orange bandana', desc:'tied to a branch, it is a thread back to the trail. the woods eat unmarked ground.' },
  /* ---- the pocket kit (pre-run loadout) ---- */
  lighter:{ name:'lighter',   desc:'a gas-station plastic lighter. worth nothing, until it is worth everything.' },
  cord:{    name:'paracord',  desc:'ten feet of cord on a bracelet. shelter lashings, wind-walls — and a tourniquet that actually holds.' },
  lamp:{    name:'headlamp',  desc:'a small headlamp. night is where the mind goes bad; light is purpose, and purpose is heat.' },
  iodine:{  name:'iodine tabs', desc:'water purification tablets. useless against salt. everywhere else, they turn fear into a drink.' },
  bars:{    name:'two energy bars', desc:'six hundred calories of pocket lint flavor. out there, a feast with two courses.' },
  wool:{    name:'wool layer', desc:'a merino base layer, worn from day one. one quiet extra degree, everywhere, always.' },
};
/* the pocket kit: what you happened to be carrying when the world turned */
const loadout = ['lighter','cord','lamp','iodine','bars','wool'];

/* ---------------- log (journal collectibles) ---------------- */
const logs = {
  l_triage:{ src:'The White Mile', line:'Bleeding first. Everything else second. I wrote it on the back of my hand so the cold couldn’t make me forget.' },
  l_firstnight:{ src:'The White Mile', line:'It isn’t the crash that kills you out here. It’s the first night, and whether you built for it before dark.' },
  l_smalltasks:{ src:'a survivor’s log', line:'I stopped looking at the whole thing. Just the next stick. Just the next sip. Just the next hour. You can always do the next small thing.' },
  l_ration:{ src:'a survivor’s log', line:'Thirst lies. It tells you to drink it all, or to drink the wrong thing. I made a rule and gave the rule my trust instead of my mouth.' },
  l_still:{ src:'The Raft', line:'Drop by drop the still gave me water out of the sea that would have killed me straight. Patience, distilled.' },
  l_routine:{ src:'The Raft', line:'The ship didn’t turn. I wrote it down, and then I did my chores anyway. The routine is a handrail in the dark.' },
  l_donttell:{ src:'The Pinch', line:'Nobody knew where I’d gone. Nobody. If I get out of this, someone will always know. That’s the whole lesson, and it cost me an arm.' },
  l_thechild:{ src:'The Pinch', line:'I saw a boy I hadn’t met yet — mine — and I was lifting him with one arm. I decided he was real. That decision is the only reason I’m writing this.' },
  l_reason:{ src:'a survivor’s log', line:'You don’t survive for yourself. You survive so you can get back to someone. Name them. Hold the name where the cold can’t reach it.' },
  l_stop:{ src:'The Trailhead', line:'STOP. Stop. Think. Observe. Plan. The hardest part is the first letter. Everything in you wants to keep walking, and the walking is what kills.' },
  l_findable:{ src:'The Trailhead', line:'I stopped hiding from the thing hunting me and started performing for the thing looking for me. Being findable is a job. I did the job.' },
  l_giardia:{ src:'The Trailhead', line:'The parasite is a next-month problem. The thirst is a today problem. I knelt down and I drank.' },
};

/* ---------------- the real ones ---------------- */
const reals = {
  koepcke:{ name:'Juliane Koepcke', what:'sole survivor of LANSA Flight 508, 1971',
    body:'A lightning strike tore her plane apart over the Peruvian Amazon and she fell two miles, still strapped to her seat. She woke alone in the rainforest with a broken collarbone. Remembering her father’s advice, she <b>found a creek and followed the moving water downstream</b> — small streams to larger ones, where people live. After <b>eleven days</b>, half-starved and with maggots in her arm, she reached a boat and a hut. Loggers found her hours later. Following water down is exactly how people get out of trackless country.' },
  callahan:{ name:'Steven Callahan', what:'76 days adrift in the Atlantic, 1982',
    body:'His sloop was holed by something in the night — likely a whale — and sank in minutes. He got into a <b>five-foot inflatable raft</b> with a ditch bag. For <b>seventy-six days</b> he ran <b>solar stills</b> for water, speared dorado with a jury-rigged spear, endured shark bumps and punctures and salt sores, and kept a disciplined routine. An <b>ecosystem grew under his raft</b>; birds gathered over it; and it was those birds that drew fishermen to him at last, near the Caribbean. He walked off the boat on his own feet.' },
  ralston:{ name:'Aron Ralston', what:'127 hours pinned in Blue John Canyon, 2003',
    body:'Canyoneering alone, he dislodged an 800-pound boulder that crushed his right wrist against the wall. <b>He had told no one where he was going.</b> For five days he rationed about <b>350 ml of water</b>, then his own urine, chipping uselessly at the rock, filming goodbyes, carving his name and a death date. Then he had a vision of <b>a future child</b> — and, on the fifth day, he <b>levered his forearm until the bones snapped and cut through the rest with a dull multitool</b>. Then he rappelled 65 feet and hiked seven miles until other hikers found him.' },
  eller:{ name:'Amanda Eller', what:'17 days lost in the Makawao Forest, Maui, 2019',
    body:'A yoga instructor went for a three-mile hike on a marked trail and stepped off it to rest. Walking back, she chose the direction she was <b>certain</b> was right — and it wasn’t. She spent <b>seventeen days</b> in the ravines: following drainages, drinking stream water, eating berries and moths, losing her shoes to a flash flood, fracturing her leg. She stayed near water and open ground, and on day 17 a <b>search helicopter</b> — funded by friends who refused to stop — spotted her waving from a creek bed between two waterfalls. She said afterward the turning point was a choice: <b>“It was a choice to live, and I had to keep making it.”</b>' },
  mind:{ name:'The ones who come back', what:'Laurence Gonzales, “Deep Survival” · History’s “Alone”',
    body:'Across every real case, the survivors are rarely the strongest or the best-equipped. They’re the ones who <b>don’t panic</b>, who <b>break the impossible into small doable tasks</b>, who <b>accept the reality they’re in</b> instead of the one they wanted, and who hold onto a <b>reason to live</b> — a person to get back to. On the show <em>Alone</em>, the body can go for weeks; it’s almost always the <b>mind that taps out first</b>. Survival is a decision you make over and over, in the cold, with no one watching.' },
};

/* ---------------- helpers ---------------- */
const helpers = {
  DEATHS:{
    white:{ thermal:'e_white_cold', water:'e_white_thirst', food:'e_white_starve', body:'e_white_bleed', grip:'e_white_giveup' },
    raft: { thermal:'e_raft_heat',  water:'e_raft_thirst',  food:'e_raft_starve',  body:'e_raft_bleed',  grip:'e_raft_giveup' },
    pinch:{ thermal:'e_pinch_cold', water:'e_pinch_thirst', food:'e_pinch_thirst', body:'e_pinch_bleed', grip:'e_pinch_giveup' },
    trail:{ thermal:'e_trail_cold', water:'e_trail_thirst', food:'e_trail_starve', body:'e_trail_fall', grip:'e_trail_giveup' },
  },
};

/* ======================================================================
   NODES
   ====================================================================== */
const nodes = {

/* ============ ORDEAL 1 — THE WHITE MILE ============ */
w_wake:{ region:'crash', title:'The Quiet After',
  text:`The engine noise is the thing you notice — that it’s gone. There was so much of it, and then a stand of spruce came up through the windshield and now there is only wind and the tick of cooling metal.\n\nThe pilot is in his seat and he is not going to help you. You don’t look twice. Your leg is warm on one side, which is wrong, because everything else is going cold. Snow is already ghosting in through the broken glass.\n\nSomewhere very far away, a rational voice reminds you: three minutes without air, three hours without shelter in this, three days without water. You have air. You do not have much of the second one.`,
  choices:[
    { t:'Find where the warm is coming from. Stop the bleeding, right now, before anything else.', pre:'first things first', grip:1, body:1, log:'l_triage', go:'w_salvage' },
    { t:'Get out and start walking for help while you still can.', myth:true, grip:-1, go:'w_lost',
      fx:S=>S.flags.bolted=1 },
    { t:'Sit still. Breathe. Let the shaking pass before you decide anything.', grip:1, go:'w_salvage' },
    { t:'Scream. Pound the door. Someone has to be coming.', grip:-1, water:-1, go:'w_salvage' },
  ]},
w_salvage:{ region:'crash', title:'Strip the Wreck',
  text:S=>`Your leg is a long shallow cut, not an artery — you pack it with a torn shirt and it holds. ${S.flags.bolted?'You came back to the plane. Good. It was a mistake to leave it.':''}\n\nThe light is already thinking about leaving. The wreck is a terrible place — fuel, glass, the pilot — but it is also a metal box full of things that could keep you alive, and it is the single most visible object for a hundred miles. A search plane looks for wreckage. It does not look for a person.`,
  choices:[
    { t:'Take everything useful: the pilot’s lighter, the knife, the mylar blanket from the kit.',
      find:'firekit', grip:1, warmth:1, fx:S=>{S.kit.includes('blade')||S.kit.push('blade');S.kit.includes('sheet')||S.kit.push('sheet');}, go:'w_salvage2' },
    { t:'The fuel stink is making you sick — get clear of the wreck and its dead man first.',
      grip:-1, go:'w_decide', fx:S=>S.flags.nokit=1 },
  ]},
w_salvage2:{ region:'crash', title:'A Mirror of Sky',
  text:`You work the polished cowling free of the nose. Held up, it throws a coin of hard white light across the snow — a signal that carries for miles on a clear day. You’ve read that a mirror flash has been seen by pilots from fifty miles out.\n\nYou have a knife, a blanket, fire in your pocket, and a way to shout with light. It is not nothing. The wolf-grey sky says you have maybe an hour before it’s too dark and too cold to build anything.`,
  choices:[
    { t:'Pry off the mirror and keep it close. Then think about the night.', find:'mirror', rescue:1, go:'w_decide' },
    { t:'Forget the mirror. Shelter is the only thing that matters now.', go:'w_decide' },
  ]},
w_decide:{ region:'crash', title:'Stay or Go',
  text:`Here is the whole game, and most people get it wrong.\n\nEvery cell in you wants to <em>move</em> — to walk until you hit a road, to do something. But you don’t know where the road is, you have no landmarks, and a person on foot in this is a needle that stops moving the moment they lie down for the last time. The wreck is warmth, materials, and a giant orange arrow for the searchers who are, right now, plotting your last known position.`,
  choices:[
    { t:'Stay with the wreck. Build a fire, a shelter, and signals here, and let them come to me.',
      pre:'the thing that keeps you alive', rescue:1, grip:1, go:'w_firstfire' },
    { t:'Follow the frozen river downstream. Moving water always leads to people, eventually.',
      go:'w_river_choice', fx:S=>S.flags.choseRiver=1 },
    { t:'Climb the ridge for a view — maybe a road, maybe a bar of phone signal.',
      go:'w_ridge' },
    { t:'Just walk toward where the road ought to be. Standing still feels like dying.',
      myth:true, grip:-1, go:'w_lost' },
  ]},
w_firstfire:{ region:'camp', title:'Building for the Dark',
  text:`The cold is not an event; it is a subtraction, and it never stops. The only reply is a fire and a wall between you and the sky.\n\nYou have maybe forty minutes of working light. This is the hour that decides it. Do it right and the night is survivable. Do it wrong — or not at all — and they find you in spring.`,
  choices:[
    { t:'Fire first, in the lee of the fuselage; then a lean-to of boughs; blanket to reflect the heat back.',
      pre:'the first night is the one that kills', item:'firekit', warmth:2, grip:1, rescue:1, log:'l_firstnight', go:'w_night' },
    { t:'The gas-station lighter in your pocket. Tonight it is the most valuable object you have ever owned. Fire, then a lean-to.',
      pre:'the pocket kit', item:'lighter', req:S=>!S.kit.includes('firekit'), warmth:2, grip:1, rescue:1, log:'l_firstnight', go:'w_night' },
    { t:'You’re thirsty and shaking. Eat handfuls of snow first, then worry about fire.',
      myth:true, warmth:-2, water:1, go:'w_night' },
    { t:'You’re exhausted. Just crawl back into the fuselage and wait it out.',
      warmth:-1, grip:-1, go:'w_night' },
  ]},
w_night:{ region:'night', title:'The Long Dark',
  text:S=>S.v.warmth<=2
    ? `The shivering stopped a while ago, and some animal part of you took that as good news. It isn’t. When the shaking stops, the cold has started winning.\n\n<span class="whisper">You feel almost warm now. Almost comfortable. The jacket feels tight, too hot, unnecessary.</span> That thought is a liar wearing your voice. People are found in the snow with their coats folded neatly beside them.`
    : `The night is enormous and completely indifferent. The fire is a small orange argument against all of it. Above the spruce the sky is impossibly clear, spilled with stars, and once a green curtain of light unrolls across it and you forget, for a second, to be afraid.\n\nSleep pulls at you. Sleep, out here, has to be earned in small careful pieces, or not taken at all.`,
  choices:[
    { t:'Feed the fire in shifts. Small logs, little sleeps, keep the shivering going — it’s heat.',
      pre:'the next stick, then the next', warmth:1, grip:1, log:'l_smalltasks', go:'w_dawn' },
    { t:'String the paracord low between two spruce and thatch it with boughs — a wind-wall, and the fire stops flinching.',
      pre:'the pocket kit', item:'cord', warmth:1, grip:1, go:'w_dawn' },
    { t:'It’s too warm in this jacket. Take it off and cool down.', myth:true, warmth:-3, go:'w_night_cold' },
    { t:'Let the fire die and sleep hard. Your body needs it.', warmth:-2, grip:-2, go:'w_dawn' },
    { t:'Name the person you’re getting back to. Say it out loud to the dark.',
      pre:'a reason is a kind of fuel', grip:2, log:'l_reason', go:'w_dawn' },
  ]},
w_night_cold:{ region:'night', title:'Paradoxical',
  text:`The relief lasts about ninety seconds. Then the real cold — the actual temperature, not the lie your dying nerves told you — closes over your bare skin like water. You reach for the jacket and your hands won’t make the shapes that hands make.\n\nThis is the mistake they warn you about, and you made it, and there is not much road left after it.`,
  choices:[
    { t:'Fight. Get the jacket back on, get to the fire, refuse this.', warmth:1, grip:-1, go:'w_dawn', noDeath:true },
    { t:'Lie back. The stars are very beautiful and you are very tired.', end:'e_white_cold' },
  ]},
w_dawn:{ region:'forest', title:'Grey Morning',
  text:S=>`You made it to light. That sentence is bigger than it sounds — most of the dying out here happens in the hours you just crossed. The fire is embers. Your body is a stiff cold argument, but it’s working.${S.v.water<=2?'\n\nYour tongue is a dry glove. You have been out here a day and barely drunk — the cold hides thirst the way the dark hides distance, and it is lying to you about how much time that clock has left.':''}\n\nSomewhere south, faint, there’s a sound your whole nervous system snaps toward: an engine. Small. Fixed-wing. Searching, maybe. Or maybe just weather in your ears.`,
  choices:[
    { t:'Throw green boughs on the fire for smoke and get ready to flash the mirror.',
      pre:'make yourself impossible to miss', rescue:1, go:'w_search', fx:S=>S.flags.readyToSignal=1 },
    { t:'Eat one of the two bars from your pocket, slowly, watching the treeline. Six hundred calories of morale.',
      pre:'the pocket kit', item:'bars', req:S=>(S.flags.bars||0)>0, food:2, fx:S=>S.flags.bars--, go:'w_dawn' },
    { t:'Save your strength — you’re weak and haven’t drunk in a day. Find water at the river first.',
      food:-1, go:'w_river_choice' },
    { t:'Stay hidden in the trees. If it’s not a rescuer, you don’t want to be found.',
      grip:-1, go:'w_search' },
  ]},
w_search:{ region:'ridge', title:'The Sound of Engines',
  text:S=>S.rescue>=S.goal
    ? `There. Banking low over the far ridge — a red-and-white Otter on floats, nose swinging, hunting the valley in slow deliberate lines. Searching. For you.\n\nEverything you did right — staying with the wreck, the signal fire, the mirror in your hand — was for exactly this thirty seconds.`
    : `It’s there — a small plane, high and to the west, not coming closer. It isn’t looking here. It doesn’t know to look here. You’re a grey speck under grey trees and the pilot’s eyes are somewhere else.\n\nYou wave. You shout. It’s pointless and you do it anyway, and then the sound thins out into nothing and the sky is empty again.`,
  choices:[
    { t:'Flash. Throw the mirror’s light straight across the cockpit glass. Again. Again.',
      item:'mirror', end:S=>S.rescue>=S.goal?'e_white_saved':null, go:'w_missed' },
    { t:'Wave your arms and the space blanket — anything bright.', item:'sheet',
      end:S=>S.rescue>=S.goal?'e_white_saved':null, go:'w_missed' },
    { t:'Just stand in the open and hope.', end:S=>S.rescue>=S.goal?'e_white_saved':null, go:'w_missed' },
  ]},
w_missed:{ region:'forest', title:'Gone Again',
  text:`The engine note bends away and dissolves. It didn’t see you. Something in your chest tries to fold up and quit.\n\nYou can sit here and wait for the next plane that may not come. Or you can accept the hard truth the country is teaching you: no one is guaranteed to come, and the moving water is the one thread out of here that you can walk yourself.`,
  choices:[
    { t:'Hold the line. Keep the fire and the mirror. They log a missed sector and fly it again.',
      grip:-1, rescue:1, go:'w_search' },
    { t:'Enough waiting. Follow the river down and out. Save yourself.',
      grip:1, go:'w_river_choice', fx:S=>S.flags.choseRiver=1 },
  ]},
w_ridge:{ region:'ridge', title:'The View Costs You',
  text:`The climb takes more than you have. Up on the bald shoulder the wind is a physical wall and it strips the heat off you in fistfuls. No road. No signal bar — of course not. But you can see the shape of the land now: the river, a silver seam running south, and far down it a paler patch that might be a lake, might be cleared ground, might be nothing.\n\nYour hands have gone stupid and white. You should not have come up here without cover, and you cannot stay.`,
  choices:[
    { t:'Get down out of the wind, fast, back to the wreck and fire.', warmth:-1, go:'w_firstfire' },
    { t:'Now you’ve seen the river’s line — commit to it and go down to the water.', warmth:-1, go:'w_river_choice' },
    { t:'Stand a moment longer and really look. Fix it in your mind.', myth:true, warmth:-2, grip:-1, go:'w_river_choice' },
  ]},
w_lost:{ region:'forest', title:'No Landmarks',
  text:`You walk. For a while it feels like progress, like doing something, like control. Then the trees close the wreck off behind you and every direction becomes the same direction. Your own tracks fill with fresh snow. The light is going and you have built nothing and gathered nothing and you do not, if you are honest, know which way you came.\n\nThis is how it happens. Not in one big mistake. In one reasonable-seeming step, and then another.`,
  choices:[
    { t:'Backtrack while you still can read your own tracks. Get back to the wreck.',
      grip:-1, go:'w_decide', fx:S=>S.flags.bolted=1 },
    { t:'Make a fire and shelter right here, right now, before dark — wherever “here” is.',
      warmth:-1, go:'w_firstfire' },
    { t:'Push on. The road has to be just over the next rise.', myth:true, warmth:-2, grip:-1, go:'w_freeze_walk' },
  ]},
w_freeze_walk:{ region:'night', title:'Just Over the Next Rise',
  text:`There is no road over the next rise. There is another rise. And the dark comes down all at once, the way it does up here, and the temperature falls off a cliff, and you have no fire and no wall and no idea where you are.\n\nYou keep walking because stopping feels like agreeing to die. But walking without shelter in this, at night, is just dying with extra steps.`,
  choices:[
    { t:'Stop. Dig into the snow, get out of the wind, save every degree you have left.',
      warmth:-1, grip:1, go:'w_night', noDeath:true },
    { t:'Keep moving. Movement is heat. Don’t stop.', myth:true, warmth:-3, go:'w_night' },
  ]},
w_river_choice:{ region:'river', title:'The Moving Water',
  text:(S,P)=>`The river is half-frozen, black water sliding fast under shelves of grey ice. It runs south — toward lower ground, toward people, the way all rivers do. Juliane Koepcke followed water like this out of the Amazon; it is one of the few reliable rules of trackless country: <em>downstream is out.</em>${P.survived&&P.survived.trail?'\n\nAnd yes — you remember a drainage that tried to eat you once, in warmer country. This is not that. That was a crack in steep rock; this is big open lowland and one broad road of water. The rule is the same rule. The terrain decides whether it’s true.':''}\n\nBut the water is snowmelt-cold, and the ice is a liar, and a soaking here at these temperatures is a death sentence you sign in about ten minutes.`,
  choices:[
    { t:'Drink first — you’re dangerously dry. Cup the running water, not the still.', water:2, go:'w_river_choice2' },
    { t:'Follow the bank downstream, slow, testing every step, staying dry above all.',
      pre:'downstream is out', rescue:1, food:-1, grip:1, go:'w_walkout' },
    { t:'The far bank is easier walking. Cross here where it looks shallow.',
      myth:true, warmth:-2, body:-1, go:'w_river_cross' },
  ]},
w_river_choice2:{ region:'river', title:'Downstream',
  text:`The water is so cold it hurts your teeth, and it is the best thing you have ever tasted. Your head clears a notch. Now: the river is the road, but only if you respect it.`,
  choices:[
    { t:'Follow the bank down, dry and patient. Hours, not heroics.',
      pre:'downstream is out', rescue:1, food:-1, grip:1, go:'w_walkout' },
    { t:'Fill the bottle, drop an iodine tablet in, and drink as you walk the bank. Hydrated is smarter, and smarter is faster.',
      pre:'the pocket kit', item:'iodine', water:2, rescue:1, food:-1, grip:1, go:'w_walkout' },
    { t:'Walk out onto the ice shelf — it’s faster than fighting the brush.',
      myth:true, body:-1, go:'w_river_cross' },
  ]},
w_river_cross:{ region:'river', title:'The Ice Lies',
  text:`The ice holds for four steps. On the fifth it doesn’t, and the river takes you in up to the chest — a cold so total it’s almost sound, a white roar that empties your lungs. The current wants you under the shelf.`,
  choices:[
    { t:'Kick, claw, throw your weight back onto solid ice. Get out. Get out NOW.',
      warmth:-2, body:-1, grip:-1, go:'w_wet', noDeath:true },
    { t:'The cold is so big there’s almost no room left to fight it.', end:'e_white_drown' },
  ]},
w_wet:{ region:'river', title:'Soaked, and the Clock Screaming',
  text:`You’re out, on your hands and knees on the ice, and you are soaking wet in killing cold. This is now the most dangerous moment of the entire ordeal. You have minutes — not many — before wet clothes conduct the last of your heat away and your hands stop working entirely.\n\nEverything depends on fire, faster than you have ever made one.`,
  choices:[
    { t:'Get to cover, strip the wet, wring it, wrap in the mylar, and build fire like your life is the timer — because it is.',
      pre:'fire or nothing', item:'firekit', warmth:1, grip:1, go:'w_walkout', noDeath:true },
    { t:'The lighter — numb thumb, three strikes, four — catch. CATCH. There. Strip the wet clothes and feed the little flame like a god.',
      pre:'the pocket kit', item:'lighter', req:S=>!S.kit.includes('firekit'), warmth:1, grip:1, go:'w_walkout', noDeath:true },
    { t:'Just keep moving to stay warm and hope the walking dries you.', myth:true, warmth:-2, go:'w_dawn' },
    { t:'Sit down. You’re so tired. Just for a second.', warmth:-2, grip:-2, go:'w_dawn' },
  ]},
w_walkout:{ region:'river', title:'One Foot, Then the Other',
  text:S=>`You follow the water down. It braids and rejoins, and the walls of the valley soften, and the spruce gives way to bigger cottonwoods that only grow where the land is kinder. ${S.days} days, now, of the next small thing and the next.${S.v.body<=1?' You walk like a broken chair — each step assembled by hand, out of parts that no longer trust each other.':''}\n\nAnd then — under the wind, so faint you distrust it — a sound that does not belong to any wilderness. A chainsaw. Or an outboard motor. Something with a spark plug in it. Something human, downstream, close.`,
  choices:[
    { t:'Follow the sound. Call out with everything you have left.',
      end:S=>(S.v.grip>=1&&S.v.body>=1)?'e_white_walkout':'e_white_giveup' },
    { t:'It’s a hallucination. The cold makes them. Don’t trust it, don’t waste your strength.',
      myth:true, grip:-2, go:'w_walkout' },
  ]},

/* ============ ORDEAL 2 — THE RAFT ============ */
r_sink:{ region:'sinking', title:'Something in the Dark',
  text:`It is 3 a.m. and the impact is a full-body event — a boom through the hull, the boat lifting and slamming down wrong. You come up the companionway into black water already at your knees. Something huge slides away under the swells, pale and enormous. A whale. The sea is coming in faster than any pump could argue with.\n\nThe raft canister is on the rail. The ditch bag — water, flares, a still, a fishing kit, everything — is below, in the flooding cabin, in the dark. You have seconds, and the boat wants to take you down with it.`,
  choices:[
    { t:'Dive back down for the ditch bag. Everything you need to live is in that bag.',
      pre:'the most important thirty seconds of your life', find:'ditchkit', grip:1, rescue:1, body:-1, log:'l_smalltasks', go:'r_raft' },
    { t:'No time — pull the canister, inflate, and get clear before the suction takes you.',
      grip:-1, go:'r_raft', fx:S=>S.flags.nobag=1 },
    { t:'Cling to the rigging. Maybe she’ll settle and float.', myth:true, grip:-2, body:-1, go:'r_raft' },
  ]},
r_raft:{ region:'raft', title:'Dawn, and the Whole Ocean',
  text:S=>`The sun comes up on a circle of orange rubber six feet across and, past its rim, the entire Atlantic in every direction, flat and bright and enormous and empty. The boat is gone. ${S.flags.nobag?'You have no bag. No water, no flares — just the raft and yourself.':'The ditch bag is in the raft with you, wet but whole. It might as well be made of gold.'}\n\nOut here the Rule of Threes rearranges itself: air you have, shelter is this raft, but water is the clock that matters and the sun is trying to boil it out of you. And the whole flat mirror of the sea is undrinkable poison.`,
  choices:[
    { t:'Rig the canopy for shade. Out of the sun, you keep your water and your head.',
      pre:'the sun is the enemy, not the cold', warmth:1, water:1, grip:1, go:'r_ration' },
    { t:'Bail the raft dry, check the buoyancy tubes, patch what you can. Make it a home.',
      grip:1, log:'l_smalltasks', go:'r_ration' },
    { t:'You can see the faint smudge of land — or think you can. Slip over and swim for it.',
      myth:true, water:-2, food:-1, go:'r_swim' },
  ]},
r_swim:{ region:'open', title:'The Smudge That Isn’t',
  text:`You swim. The smudge does not get closer, because the smudge is a cloud, or your own hope drawn on the horizon. The raft, when you turn back in a spike of panic, is already smaller than it should be.\n\nThe open ocean does not forgive swimming. It is too big, you are too small, and everything down there is interested in a thrashing animal at the surface.`,
  choices:[
    { t:'Get back to the raft. NOW. While you still can see it. Never leave it again.',
      water:-1, grip:-1, go:'r_ration', noDeath:true },
    { t:'Keep swimming for the smudge. Commit.', myth:true, end:'e_raft_shark' },
  ]},
r_ration:{ region:'raft', title:'The Water Rule',
  text:(S,P)=>`${S.flags.nobag?'You have no stored water at all. Every drop now has to come from the sky or from the sea, made drinkable by patience you have to invent.':'You inventory the water: a few tins. Days, not weeks. It will not stretch to a rescue on its own.'}${P.survived&&P.survived.white?'\n\nYou have been rationed by a wilderness before — but the cold at least was honest about being your enemy. The sun is worse company. It feels like a friend while it bleeds you.':''}\n\nThirst is about to become the loudest voice in your head, and it is a liar. It will tell you to drink it all now. It will tell you, when the tins are gone, to drink the sea. Both are ways of dying faster while feeling like you did something.`,
  choices:[
    { t:'Make a rule: tiny measured sips, dawn and dusk only. Then obey the rule, not the thirst.',
      pre:'thirst lies', grip:1, log:'l_ration', go:'r_still' },
    { t:'Eat one of the two bars, in eight small bites, over an hour. A meal is a decision to keep being a person.',
      pre:'the pocket kit', item:'bars', req:S=>(S.flags.bars||0)>0, food:2, fx:S=>S.flags.bars--, go:'r_ration' },
    { t:'Drink deeply now — a clear head is worth more than a reserve you might never spend.',
      myth:true, water:1, grip:-1, fx:S=>S.flags.drankdeep=1, go:'r_still' },
    { t:'The sea is <em>right there</em>, endless. Surely a few mouthfuls—',
      myth:true, water:-2, grip:-2, body:-1, go:'r_seawater' },
  ]},
r_seawater:{ region:'raft', title:'The Sea Says Drink',
  text:`It is cool and wet and for one glorious second it is everything you wanted. Then the salt does its arithmetic. To flush the salt you took in, your kidneys have to spend <em>more</em> fresh water than you drank — water pulled out of your own tissues. You will be thirstier now than before you drank, and then thirstier, and the thirst will start to sound like a voice, and then the voice will start to make sense.\n\nEvery sailor’s manual ever written puts it in italics: <em>never drink seawater.</em>`,
  choices:[
    { t:'Spit it out, stop, and never again. Rebuild from here.', grip:1, go:'r_still', noDeath:true },
    { t:'It helped, though. Didn’t it? Have a little more.', myth:true, end:'e_raft_thirst' },
  ]},
r_still:{ region:'open', title:'Water From Nothing',
  text:S=>`${S.kit.includes('ditchkit')?'The ditch bag has a solar still — a clear bag that lets the sun evaporate seawater and drip it back down, salt left behind. A few precious ounces a day. It is the difference between weeks and days.':'You have no still — so you improvise one from the canopy sheet, angling it to catch condensation at dawn, and you pray for rain.'}\n\nSteven Callahan ran stills like this for seventy-six days. It is slow, fiddly, unglamorous work, and it is exactly the kind of small patient task that keeps a person both hydrated and sane.`,
  choices:[
    { t:'Set up the still, tend it every day, protect it like a child. Drop by drop.',
      pre:'patience, distilled', find:'still', water:2, grip:1, log:'l_still', go:'r_fish' },
    { t:'A squall is building on the horizon — rig everything you have to catch rainwater.',
      water:2, warmth:-1, go:'r_fish' },
    { t:'It’s hopeless arithmetic. Lie back under the canopy and stop fighting it.',
      grip:-2, go:'r_fish' },
  ]},
r_fish:{ region:'raft', title:'The Garden Under the Raft',
  text:`Days pass. Something strange and hopeful happens: the raft grows a shadow-world. Barnacles fur the underside; small fish come to hide in that shade; bigger fish — dorado, gold and furious — come to hunt the small ones; and where there are fish, eventually, there are birds.\n\nCallahan speared dorado from his raft and ate them raw, drinking the fluid from their eyes and spines for moisture. The sea is trying to kill you and, if you’re patient and clever, also trying to feed you.`,
  choices:[
    { t:'Lash the knife to an oar and make a gaff. Fish slow, fish patient, waste no motion.',
      pre:'the sea has a pantry if you can hold on', find:'gaff', food:2, grip:1, log:'l_smalltasks', go:'r_sharks' },
    { t:'Snatch at them with your bare hands — you’re starving, you can’t wait.',
      myth:true, food:-1, body:-1, go:'r_sharks' },
    { t:'You can’t stomach the thought of raw fish. Wait for rescue instead.',
      food:-1, grip:-1, go:'r_sharks' },
  ]},
r_sharks:{ region:'raftnight', title:'Bumps in the Night',
  text:`In the dark something the size of a door rises under the raft and shoves. Then again — a slow, deliberate, testing bump that lifts you and sets you down. The gold fish have drawn grey ones. A fin creases the moonlit water and turns.\n\nEverything in you wants to thrash, to scream, to stab at the water. All of it is exactly wrong. A raft is not prey; a panicking splashing animal half-out of it might be.`,
  choices:[
    { t:'Go still. Pull your limbs in, breathe slow, wait it out. Give the sea nothing to hunt.',
      pre:'do not become prey', grip:1, go:'r_ship' },
    { t:'Lash yourself and every loose thing to the raft with the paracord. Then go still — a tied-down thing cannot be spilled.',
      pre:'the pocket kit', item:'cord', grip:1, body:1, go:'r_ship' },
    { t:'Stab down at it with the gaff to drive it off.', item:'gaff', myth:true, body:-1, go:'r_shark_bad' },
    { t:'Thrash and scream and beat the water — make yourself big and scary.',
      myth:true, body:-1, grip:-1, go:'r_shark_bad' },
  ]},
r_shark_bad:{ region:'raftnight', title:'Blood in the Water',
  text:`The gaff skids off sandpaper hide and the shark rolls, unbothered, and comes back with interest. Your arm is in the water when it does. There is a shock of pressure, no pain yet — pain is a message that takes a moment to arrive — and then a warm dark cloud spreading in the moonlit water, which is yours.`,
  choices:[
    { t:'Get the arm in, jam it against your body, stop the bleeding, DON’T pass out.',
      body:-1, grip:-1, go:'r_ship', noDeath:true },
    { t:'The water is very dark and getting darker.', end:'e_raft_bleed' },
  ]},
r_ship:{ region:'open', title:'A Light on the Rim of the World',
  text:S=>`Lights. Low on the horizon, steady, moving — a ship. The first proof in days or weeks that the human race still exists. It is miles off and it does not know you are a speck of orange in a billion square miles of water.\n\n${S.kit.includes('ditchkit')?'You have flares. A handful of them. Each one is a single question fired into the dark: <em>are you looking?</em>':'You have no flares. Only your arms, the pale canopy, and your voice.'}`,
  choices:[
    { t:'Fire a flare — and be ready to fire another the instant you think they might look.',
      item:'ditchkit', rescue:2, go:'r_ships_result' },
    { t:'Strobe the headlamp at the lights — S O S, slow and deliberate, aimed like a rifle across the miles.',
      pre:'the pocket kit', item:'lamp', rescue:1, go:'r_ships_result' },
    { t:'Wave the canopy, catch the moon on the signal, scream until your throat tears.',
      rescue:1, water:-1, go:'r_ships_result' },
    { t:'Paddle toward it with your hands. Close the distance.', myth:true, water:-1, food:-1, go:'r_ships_result' },
  ]},
r_ships_result:{ region:'open', title:'It Doesn’t Turn',
  text:S=>`You watch the lights the whole way across the horizon, and they never change heading. No answering flash. No horn. The ship carries its warm lit rooms and its sleeping crew right past you and over the curve of the earth, and the dark closes back up where it was.${S.v.grip<=2?'\n\n<span class="whisper">And a small reasonable voice, in your own accent, says: that was the one. That was yours, and it’s gone, and there is a kind of rest in admitting arithmetic.</span> The voice is not you. Salt and thirst wear your voice when they talk.':''}\n\nCallahan watched ships pass him too. This is the moment that breaks people — not the thirst, not the sun. The nearness of rescue, withdrawn. What you do in the next sixty seconds is the whole thing.`,
  choices:[
    { t:'Write it in the log. Then tend the still, check the lines, do the chores anyway.',
      pre:'the routine is a handrail in the dark', grip:2, log:'l_routine', go:'r_birds' },
    { t:'Save your last flares. There will be other ships. There have to be.',
      grip:-1, rescue:1, go:'r_birds' },
    { t:'That was the one. That was rescue and it left. There’s no point to any of this.',
      myth:true, grip:-3, go:'r_birds' },
  ]},
r_birds:{ region:'raft', title:'The Birds Know Something',
  text:S=>`Weeks, now. You are a smaller, saltier, harder animal than the one the boat went down with. And one morning the birds are back — not passing over, but <em>circling</em>, working the water around your raft, diving on the little ecosystem you’ve been dragging across the ocean like a slow green comet.\n\nBirds over a raft is a sign you can’t read but a fisherman can. It was birds that finally drew a boat to Callahan — not his flares, not his will, but the life that had gathered under him.`,
  choices:[
    { t:'Keep the signals up, keep the still running, trust that the birds are telling someone.',
      pre:'the life under you is calling out for you', rescue:1, grip:1, go:'r_climax' },
    { t:'You’re too weak to sit up. Let the birds do whatever birds do.',
      grip:-1, go:'r_climax' },
  ]},
r_climax:{ region:'open', title:'A Hull, Where There Was Only Sea',
  text:S=>`There — following the birds in, low and battered and beautiful, a fishing boat, its crew already pointing, already turning toward the impossible orange dot that is you. Diesel smoke. Human shouting. A face, sunburned and astonished, leaning over a gunwale toward you.\n\nAfter everything the ocean took, it turns out the sea also grew you a rescue, out of barnacles and small fish and birds and one animal too stubborn to drink it.`,
  choices:[
    { t:'Raise your arm. Let them see you’re alive. Let them take you home.',
      end:S=>S.rescue>=S.goal?'e_raft_saved':'e_raft_land' },
    { t:'It’s another mirage. The sea does this. Don’t believe it, don’t break your own heart.',
      myth:true, grip:-2, end:S=>S.rescue>=S.goal?'e_raft_saved':'e_raft_land' },
  ]},

/* ============ ORDEAL 3 — THE PINCH ============ */
p_shift:{ region:'slot', title:'Eight Hundred Pounds',
  text:`The canyon is barely shoulder-wide here, a crack in the desert’s bones, and you are down-climbing a chockstone when it moves. A boulder the weight of a small car shifts under your hand, drops, and stops — with your right forearm crushed between it and the wall.\n\nThe sound you make isn’t a word. The pain arrives a half-second late and then arrives completely. You pull. It doesn’t move a hair. You are, very suddenly and very literally, part of this canyon now.\n\nAnd the thought under all the other thoughts, cold and clear: <em>no one knows I’m here. I didn’t tell a soul.</em>`,
  choices:[
    { t:'Breathe. Do not panic. Panic burns water and clarity you can’t spare. Assess.',
      pre:'panic is the first thing that kills you', grip:1, log:'l_donttell', go:'p_assess' },
    { t:'Scream for help. Scream until it’s all gone.', water:-1, grip:-1, go:'p_assess' },
    { t:'Throw your whole body against the boulder, again, again, again.',
      myth:true, body:-1, go:'p_assess' },
  ]},
p_assess:{ region:'slotday', title:'The Inventory',
  text:`You force yourself to catalogue, out loud, like reading a checklist to a frightened stranger who happens to be you. Water: less than a litre, maybe 350 millilitres after that scream. Food: a couple of bites. Kit: a cheap multitool with a dull little blade. Light and warmth: the sky is a blue ribbon far overhead, and down here it will bake by noon and freeze by night.\n\nThe arm is the whole problem. Everything else is just the clock.`,
  choices:[
    { t:'Chip at the chockstone with the multitool. Methodical, hour after hour. Try everything gentle first.',
      pre:'the next small thing, and the next', day:1, grip:1, log:'l_smalltasks', go:'p_ration' },
    { t:'Rig a haul — anything, your pack straps, leverage — and try to lift the boulder off.',
      day:1, body:-1, go:'p_ration' },
    { t:'Wrench and twist your own arm, tear it free by force if you have to.',
      myth:true, body:-1, grip:-1, go:'p_ration' },
  ]},
p_ration:{ region:'slotday', title:'Three Hundred and Fifty Millilitres',
  text:`The rock does not care about your multitool; you’ve scratched a pale patch the size of a coin and nothing more. Hours have gone. The sun found the slot and left it, and the water in your bottle is a small terrible number that only goes down.\n\nRalston made this much water last five days here. It can be done. It is done by treating each sip like a decision, not a reflex — and, when the bottle is empty, by drinking what your own body gives back, and not being too proud to.`,
  choices:[
    { t:'Ration it to the milliliter. When it’s gone, save your urine and drink that. Buy days.',
      pre:'not too proud to live', water:1, grip:1, log:'l_ration', go:'p_nights' },
    { t:'One of the two bars. Ralston had two burritos and made them last five days. You know the arithmetic of small food now.',
      pre:'the pocket kit', item:'bars', req:S=>(S.flags.bars||0)>0, food:2, fx:S=>S.flags.bars--, go:'p_ration' },
    { t:'Drink it down — the clear-headedness is worth more than the reserve.',
      myth:true, water:1, grip:-1, fx:S=>S.flags.drankit=1, go:'p_nights' },
    { t:'Scratch your name and today’s date into the wall. Just in case. Just so they know.',
      grip:-1, rescue:1, fx:S=>S.flags.carved=1, go:'p_nights' },
  ]},
p_nights:{ region:'slotnight', title:'The Cold Comes Up the Canyon',
  text:(S,P)=>`People think the desert is heat. The desert is heat and then, the instant the sun leaves, a cold that pours down the slot like water and settles into your pinned, exhausted, dehydrated body. You cannot move to warm yourself. You cannot make a fire with one hand and no wood. You can only shiver, and shivering is the body spending fuel it doesn’t have to buy heat it can’t keep.${P.survived&&(P.survived.white||P.survived.raft)?'\n\nYou have crossed long nights before — you know their size, and that they end. That knowledge is worth one degree, maybe two. Out here you count wealth in single degrees.':''}\n\nThe nights are longer than the days. Each one is a small siege.`,
  choices:[
    { t:'Work your free limbs, clench and release, keep the blood moving, ration every degree.',
      pre:'small motions, big difference', warmth:1, grip:1, go:'p_visions' },
    { t:'Click the headlamp on low and keep working the rock through the dark. Motion is heat. Purpose is heat.',
      pre:'the pocket kit', item:'lamp', warmth:1, grip:1, go:'p_visions' },
    { t:'Curl in and let the shivering fade. It’s using energy you don’t have.',
      myth:true, warmth:-2, go:'p_visions' },
    { t:'Talk. Out loud. To your family, to the dark, to anyone. Keep a human voice in the canyon.',
      pre:'a reason is a kind of fuel', grip:1, log:'l_reason', go:'p_visions' },
  ]},
p_visions:{ region:'slot', title:'The Fifth Day',
  text:S=>`Day ${Math.max(S.days,4)}, by a tally you have stopped trusting. Time has come apart. The water is gone; you’ve been drinking your own, and even that is nearly nothing. Your body is eating itself and your mind, starved and cooked and frozen by turns, has started to show you things.\n\nA sofa, impossibly, at the bottom of the canyon. Sunlight that isn’t there. And then — clear as anything you have ever seen — <em>a small blond boy, and you are lifting him up onto your shoulder, and you are doing it with one arm, because you only have one.</em> A child you have not met. A future, insisting on itself.\n\nRalston saw exactly this. He said afterward it was the moment he decided to live — because now there was someone to live <em>for</em>.`,
  choices:[
    { t:'Take the boy as a promise, not a hallucination. Decide he is real. Decide to get to him.',
      pre:'name the reason and hold it', grip:2, log:'l_thechild', fx:S=>S.flags.sawchild=1, go:'p_choice' },
    { t:'Record your goodbyes. Make your peace. Accept that this is where it ends.',
      grip:-1, fx:S=>S.flags.goodbye=1, go:'p_choice' },
    { t:'There’s nothing to live for down here. Let go. Let the canyon have you.',
      myth:true, grip:-3, go:'p_choice' },
  ]},
p_choice:{ region:'slot', title:'The Only Door',
  text:S=>`And now you understand the thing you have been refusing to understand for five days, the thing your whole animal self has been screaming against: the arm is not coming out of the rock. <em>You</em> are coming out. Without it.\n\nThe multitool’s blade is dull as a butter knife and too short to be doing what it will have to do. But you’ve worked out that if you torque your forearm hard against the stone, the leverage will snap the two bones — and once the bones are gone, the dull little blade only has to get through the soft parts. It is the most terrible arithmetic a person can do. It is also, precisely, the way out.`,
  choices:[
    { t:'The paracord first — a true tourniquet, cinched down with a stick, tight past feeling. Then the bones. Then the blade.',
      pre:'the cord holds what the cloth cannot', item:'cord', req:(S)=>S.v.grip>=3, body:-1, grip:-1, end:'e_pinch_cut' },
    { t:'Break the bones against the stone. Then the tourniquet. Then the blade. Get to the boy.',
      pre:'the only way out is through', item:'multitool', req:(S)=>S.v.grip>=3&&!S.kit.includes('cord'), body:-2, grip:-1, end:'e_pinch_cut' },
    { t:'You can’t. It’s not human. Wait one more day — maybe someone comes.',
      day:1, water:-1, grip:-1, go:'p_wait' },
    { t:'Rest your head against the cool rock and stop. You’re so tired.',
      grip:-2, go:'p_wait' },
  ]},
p_wait:{ region:'slotnight', title:'No One Comes',
  text:S=>`You wait. Of course you wait — waiting is easier than the alternative, and the alternative is unthinkable. But the canyon stays empty, because you told no one, because the desert is vast, because rescue is a story people tell and not a thing that is owed to you.\n\n${S.v.grip>=3?'And somewhere in the waiting, the boy is still there behind your eyes, still insisting, and the thing you couldn’t do starts to look less impossible than dying twenty feet from your own two legs.':'The waiting is starting to feel like a decision. A soft one. The kind you don’t come back from.'}`,
  choices:[
    { t:'Enough. The cord tourniquet, cinched past feeling — then the bones, then the blade, then the boy.',
      pre:'the cord holds what the cloth cannot', item:'cord', req:(S)=>S.v.grip>=3, body:-1, grip:-1, end:'e_pinch_cut' },
    { t:'Enough. There is one door and you are going to walk through it. The bones, then the blade.',
      pre:'through', item:'multitool', req:(S)=>S.v.grip>=3&&!S.kit.includes('cord'), body:-2, grip:-1, end:'e_pinch_cut' },
    { t:'Wait longer. Someone will come. Someone has to come.', myth:true, day:1, water:-1, grip:-1, go:'p_wait' },
    { t:'Close your eyes. Let it be over.', end:'e_pinch_giveup' },
  ]},

/* ============ ORDEAL 4 — THE TRAILHEAD ============ */
t_step:{ region:'trailday', title:'Thirty Seconds',
  text:`The trail is a good one — maintained, blazed, climbing through big ponderosa in bars of morning light. A three-hour loop. You told the front desk you'd be back by two, more or less, and "more or less" felt like plenty of precision at the time.\n\nTwo miles up, your body files a request that isn't optional. There's decent cover maybe forty yards off-trail, behind a granite block the size of a garage.\n\nForty yards. Thirty seconds. This is the most dangerous moment of your entire year, and it is wearing the costume of the most boring one.`,
  choices:[
    { t:'Tie your orange bandana to a branch at the trail’s edge first. Then step off.',
      pre:'a thread back', find:'bandana', grip:1, fx:S=>S.flags.marked=1, go:'t_back' },
    { t:'Just step off. It’s forty yards. You can hear the trail from there.', myth:true,
      fx:S=>S.flags.nomark=1, go:'t_back' },
    { t:'Drop a pin on your phone first — battery’s at forty percent, but still.',
      item:'phone', fx:S=>S.flags.pinned=1, go:'t_back' },
  ]},
t_back:{ region:'offtrail', title:'The Forest Closes',
  text:S=>`${S.flags.marked?'Business done, you head back toward the bandana — and the woods have quietly rearranged themselves. Same trees. Same light. No orange anywhere.':'Business done, you walk back toward the trail. Forty yards. Then sixty. The trail should be here. The trail is not here.'}\n\nYou stop. You turn a slow circle, and every direction is the same photograph: pine, granite, duff, light. The trail — a thing four feet wide and utterly obvious an hour ago — has been deleted from the world.\n\nA small hot bubble rises in your chest. It has two ingredients: fear, and — worse — <em>embarrassment</em>. People die of the second one. They stay quiet, they don't backtrack, they press on, because being lost forty yards from a marked trail is <em>ridiculous</em>.`,
  choices:[
    { t:'Sit down. Right now, on this rock. Stop. Think. Observe. Plan.',
      pre:'the first letter is the hard one', grip:1, log:'l_stop', go:'t_stop' },
    { t:'It’s forty yards. Walk back the way you came — you KNOW the way you came.', myth:true,
      go:'t_bend' },
    { t:'Swallow the embarrassment and shout for help. Loud. Now, while someone might still be near.',
      pre:'pride is not a vital sign', grip:1, fx:S=>S.flags.shouted=1, go:'t_stop' },
  ]},
t_bend:{ region:'offtrail', title:'Bending the Map',
  text:`You walk the way you came. Ten minutes later you have not found the trail, which is impossible, so you keep going, because it has to be just ahead — and there, see, that leaning snag looks familiar. You're fine. That boulder — familiar. You're fine.\n\nThere is a name for what your brain is doing. Searchers call it <em>bending the map</em>: when the world stops matching your mental picture, and instead of redrawing the picture, you bend the world to fit it. Every landmark becomes "familiar." Every wrong step gets a justification.\n\nThe snag was not familiar. You have never been here in your life.`,
  choices:[
    { t:'Stop moving. Say it out loud, the ridiculous sentence: "I am lost."',
      pre:'the map is bent — unbend it', grip:1, log:'l_stop', go:'t_stop' },
    { t:'One more rise. The trail is over the next rise. It has to be.', myth:true,
      food:-1, go:'t_bend2' },
    { t:'Look for your own footprints in the duff and follow them back.',
      food:-1, body:-1, go:'t_stop', fx:S=>S.flags.tracked=1 },
  ]},
t_bend2:{ region:'offtrail', title:'The Next Rise',
  text:`The next rise shows you another rise. The one after that shows you a deadfall maze that takes twenty scratching minutes to cross and deposits you somewhere with less light and no rises at all.\n\nYou have now walked — what, an hour? — in the confident direction. Search and rescue has a statistic that would freeze your blood: most lost hikers are found within two miles of where they left the trail. The ones found alive are usually the ones who stopped early. The confident direction is how the two miles become ten.\n\nThe light is going amber. The afternoon is spending itself. And the hot bubble in your chest has grown teeth.`,
  choices:[
    { t:'Sit. Breathe until the panic drains. Then — Stop. Think. Observe. Plan.',
      pre:'late is better than never', grip:1, log:'l_stop', go:'t_stop' },
    { t:'RUN. Downhill. Down always leads out. GO.', myth:true, body:-1, warmth:-1, go:'t_creek' },
    { t:'Climb a tree. See over the deadfall. Get one honest look at the country.',
      body:-1, fx:S=>S.flags.treeview=1, go:'t_stop' },
  ]},
t_stop:{ region:'offtrail', title:'Stop. Think. Observe. Plan.',
  text:S=>`You sit still, and for the first time since the garage-sized boulder, your brain is allowed to be smart instead of certain.\n\n<em>Think.</em> You crossed no creek walking in — so the drainage below you is new country, not the way back. The road, and the trailhead, were west. It is now ${S.flags.treeview?'late afternoon — from the tree you saw an ocean of unbroken forest, one bald granite dome to the north, and no roads —':'late afternoon'} and the light has maybe three hours left.\n\n<em>Observe.</em> The clouds are stacking grey in the west. The forecast at the front desk said tonight: rain, mid-forties. That is not "cold." That is worse — that is hypothermia weather nobody takes seriously.\n\n<em>Plan.</em> Three doors, and the rest of your life behind one of them.`,
  choices:[
    { t:'Stay. Make this your ground: shelter for the rain, signals for the searchers, near the clearing uphill.',
      pre:'the found ones are the ones who stopped', rescue:1, fx:S=>S.flags.stay=1, go:'t_prep' },
    { t:(S,P)=>P.survived&&P.survived.white
        ?'Follow the drainage down. The frozen river carried you out of the white once — water leads to people. It’s the rule that saved your life.'
        :'Follow the drainage down. Moving water leads to people — everyone knows that.',
      go:'t_creek' },
    { t:'Climb the bald dome to the north. Height means phone signal. One text out changes everything.',
      go:'t_ridge' },
  ]},
t_ridge:{ region:'ridgeview', title:'One Bar, Maybe',
  text:`The dome costs you an hour and most of your legs, and it pays you in perspective you did not want: forest to every horizon. No roads. No rooftops. No smoke. Just an ocean of green with you drowned somewhere in it.\n\nYou hold the phone at arm's length toward the sky like an offering. One bar flickers — appears, dies, appears. A signal the width of an eyelash.\n\nBattery: 31%. This phone is the only machine that knows you exist. What you spend it on now is the whole game.`,
  choices:[
    { t:'One text — to 911 and to your person: lost near the loop trail, north dome, staying put nearby. Hold it high. Then airplane mode.',
      pre:'texts queue and slip through cracks calls can’t', item:'phone', rescue:2, grip:1,
      fx:S=>S.flags.texted=1, go:'t_prep' },
    { t:'Call 911. Keep redialing until a human voice answers. A text is a message in a bottle.', myth:true,
      item:'phone', fx:S=>S.flags.deadphone=1, go:'t_prep' },
    { t:'Stay up here overnight — keep line-of-sight for the signal. The exposed rock is worth it.', myth:true,
      warmth:-2, go:'t_night' },
  ]},
t_creek:{ region:'creekbed', title:'The Water Argument',
  text:(S,P)=>`The drainage starts as a friendly idea — a damp seam, a trickle you can step over, going <em>down</em>, and down is out. ${S.flags.shouted?'You even shout again as you go, into the white noise of moving water, which eats your voice whole.':''}\n\nAn hour in, the friendly idea has walls. The trickle is a creek, the creek runs between granite blocks the size of vans, wet and skinned with algae, and the forest overhead has closed into a green ceiling no helicopter will ever see through.\n\nHere is the cruel print at the bottom of the survival contract: <em>follow water to people</em> is jungle advice, river advice, big-country advice.${(P.survived&&P.survived.white)?' You of all people know it works — you walked a frozen river out of the worst country of your life. But that river was a road. This is a crack.':''} In steep granite parks the drainages are where day-hikers break ankles, where the brush is thickest, where searchers find what they find. The rule that saves you in one wilderness kills you in another.\n\nBut the water itself — cold, clear, loud — is real, and your mouth has been paper for hours.`,
  choices:[
    { t:'Drink. Kneel down and drink your fill. Giardia is a next-month problem; thirst is a today problem.',
      pre:'drink the water', water:2, log:'l_giardia', go:'t_creek2' },
    { t:'Don’t risk untreated water — you’ve read about parasites. Keep your discipline.', myth:true,
      water:-1, go:'t_creek2' },
  ]},
t_creek2:{ region:'creekbed', title:'The Gorge Says No',
  text:`Around the next bend the drainage plays its card: a twelve-foot pour-over, granite polished glass-slick by ten thousand years of spring melt, with a jam of dead logs wedged in the pool below like snapped bones.\n\nDown there the walls are steeper. The brush is worse. The light is a rumor. Every step of descent is a step a stretcher can't be carried back up.\n\nThe drainage is not a path. It is a drain. Things go down it and do not come back.`,
  choices:[
    { t:'Accept the hour you wasted. Climb OUT of the drainage to open ground, and make your stand there.',
      pre:'a wasted hour is not a wasted life', grip:1, rescue:1, fx:S=>S.flags.stay=1, go:'t_prep' },
    { t:'Downclimb the pour-over. Careful. Slow. It’s only twelve feet.', myth:true,
      body:-2, go:'t_fall', noDeath:true },
    { t:'Wade the pool and squeeze through the log jam instead.', myth:true,
      warmth:-2, body:-1, go:'t_fall', noDeath:true },
  ]},
t_fall:{ region:'creekbed', title:'The Drain',
  text:`The granite takes your feet out the way a rug is pulled — no malice, no warning, just physics collecting a debt. You hit the log jam with your hip and something in your ankle reports in a voice you've never heard it use.\n\nYou lie half in the water, which is doing to your body heat what the gorge does to daylight. The ankle will take weight, barely, at a price. You are wet, hurt, and deep in a slot in the earth exactly one helicopter-width too narrow to be seen from.\n\nThis is where the statistic lives. This is the place the searchers mean when they say <em>drainages</em>.`,
  choices:[
    { t:'Get OUT. Crawl, claw, whatever it costs — up out of the gorge to open ground before dark.',
      pre:'out of the drain, whatever it costs', food:-1, grip:1, fx:S=>S.flags.stay=1, go:'t_prep', noDeath:true },
    { t:'You can’t climb. Shelter here, under the logs, out of the wind.', warmth:-1, go:'t_night' },
  ]},
t_prep:{ region:'meadow', title:'Becoming Findable',
  text:S=>`${S.flags.stay?'Open ground, at last: a small meadow, knee-deep in dry grass, with a granite slab shouldering out of one edge.':'You reach flatter, opener ground as the light goes long.'} The clouds in the west have finished stacking and started moving.\n\nTwo jobs before dark, and they pull in opposite directions.\n\nThe rain job: shelter — bark and boughs against the slab, a roof, a floor of duff a foot thick, small and tight and dry.\n\nThe search job: <em>visibility</em> — because here is the truth almost nobody acts on: hiding from the weather and hiding from the searchers look identical from a helicopter. People survive the night in perfect little dens and are flown past for a week. Being findable is not a mood. It is a job with tasks.`,
  choices:[
    { t:'Shelter first — tight, dry, insulated. You can be visible at dawn; you can’t be visible dead.',
      pre:'live first, wave second', warmth:2, grip:1, go:'t_night' },
    { t:'Signals first while the light holds: stake the orange tarp flat in the open, spread your gear, three whistle blasts, again, again.',
      item:'tarp', pre:'being findable is a job', rescue:1, warmth:-1, log:'l_findable', go:'t_night' },
    { t:'Paracord between two pines, the tarp pitched drum-tight over a duff bed at the meadow’s edge — shelter that IS a signal.',
      pre:'the pocket kit', item:'cord', req:S=>S.kit.includes('tarp'), warmth:1, rescue:1, grip:1, log:'l_findable', go:'t_night' },
    { t:'Split the hour: half a shelter, the tarp half-staked, whistle between armfuls of wood.',
      warmth:1, rescue:1, food:-1, go:'t_night' },
  ]},
t_night:{ region:'stormnight', title:'Forty-Five and Raining',
  text:S=>S.v.warmth<=2
    ? `The rain arrives like a decision. Forty-five degrees, the forecast said, and you'd have shrugged at that number in a parking lot.\n\nYou are not in a parking lot. You are wet to the skin in moving air, and forty-five wet steals heat faster than twenty dry. The shivering has climbed from your hands into your trunk, big rolling shudders — your body burning its pantry to keep the lights on. <span class="whisper">And underneath it, faint, the first soft wrongness: the rain sounds almost like voices. The dark has corners it didn't have.</span>\n\nMost hypothermia deaths happen between thirty and fifty degrees. Nobody fears the forties. That is what makes them lethal.`
    : `The rain arrives like a decision, and your shelter meets it — drips, seeps, but holds. Forty-five degrees of steady water on everything you own, and you are a small dry animal in a small dry pocket, listening.\n\nThe night is fourteen hours long. Nobody tells you that about being lost: the nights are the size of oceans. You cross them in strokes — a handful of duff stuffed into your jacket, a recount of the whistle blasts, a knuckle of trail mix held on the tongue.`,
  choices:[
    { t:'Ration the night in small tasks: duff in the clothes, knees to chest, count breaths to a hundred, again.',
      pre:'the next small thing', warmth:1, grip:1, log:'l_smalltasks', go:'t_morning' },
    { t:'The lighter, under the slab’s dry overhang, fed with the underside of deadfall — a fire in the rain. An impossible little sun.',
      pre:'the pocket kit', item:'lighter', warmth:2, grip:1, go:'t_morning' },
    { t:'The rain’s easing — night-hike out by phone light. Moving is warmth. Sitting is dying.', myth:true,
      item:'phone', warmth:-2, body:-1, fx:S=>S.flags.nighthike=1, go:'t_morning' },
    { t:'Say your person’s name into the rain. Tell them about tomorrow. Promise it.',
      pre:'a reason is a kind of fuel', grip:2, log:'l_reason', go:'t_morning' },
  ]},
t_morning:{ region:'meadow', title:'The Grey Miles of Morning',
  text:S=>`Dawn comes up the color of dishwater, and you are still here — stiff, hollowed, ${S.flags.nighthike?'three panicked night-miles from wherever you were, which cost you and bought nothing,':''} but breathing.${S.v.water<=1?' Your mouth has stopped making spit. That is not a detail; that is a deadline.':''} Day ${S.days+1}. Overdue since two o'clock yesterday. Somewhere down the mountain, a front-desk clerk has told someone, who has told someone, whose job is you now.\n\nAnd then you hear it — far off, low, rhythmic. A helicopter, working a grid. The sound swells… holds… and bends away, thorough and patient and <em>somewhere else</em>.\n\nThey are looking. They are looking in the wrong square. Your entire job today is to change which square is worth looking at.`,
  choices:[
    { t:'Work the camp: smoke on the fire, tarp X squared to the sky, three blasts on the whistle till your ears ring.',
      pre:'perform for the ones looking', item:'whistle', day:1, rescue:1, food:-1, go:'t_search' },
    { t:'Tablet a bottleful from the seep below the meadow and drink it all. Clear-headed is the whole job now.',
      pre:'the pocket kit', item:'iodine', day:1, water:2, rescue:1, go:'t_search' },
    { t:'One of the two bars, and the last of your patience with it — breakfast for the performance ahead.',
      pre:'the pocket kit', item:'bars', req:S=>(S.flags.bars||0)>0, food:2, fx:S=>S.flags.bars--, go:'t_morning' },
    { t:'Chase it. Grab everything and move toward where the sound went.', myth:true,
      day:1, food:-1, grip:-1, go:'t_search' },
    { t:'Forage first — grubs under the deadfall, manzanita berries, anything. You’re running on nothing.',
      day:1, food:1, water:-1, go:'t_search' },
  ]},
t_search:{ region:'meadow', title:'The Sound Comes Back',
  text:S=>S.rescue>=S.goal
    ? `Late morning, the grid brings it back — lower this time, following the drainage line, and then it stops being a sound and becomes a <em>thing</em>, a white-and-red machine hammering the air over your meadow, and the orange X is up, and the smoke is up, and you are in the open with your arms making the biggest Y of your life.\n\nThe helicopter tilts. Holds. Comes back around.\n\nEverything you did — the stopping, the staying, the tarp, the whistle, the performed and unglamorous business of being findable — was for exactly this pass.`
    : `It comes back through twice more across the day, always with that patient, methodical distance — a machine reading squares of forest like lines of print, and your square not yet on the page. Once it passes close enough to shake the treetops, and you scream into the rotor-wash, which is like screaming into the sea.\n\nBy the time the light goes long, the sound has gone south, and the forest is just a forest again, enormous and neutral.\n\nYou know what improves the odds. You've known all along. The question is only whether you keep doing the job.`,
  choices:[
    { t:'Signals up. Arms up. Be the most visible thing this forest has grown in a century.',
      end:S=>S.rescue>=S.goal?'e_trail_found':null, go:'t_lastcall' },
    { t:'It’s not coming back. Nobody’s coming. Stop performing for an empty sky.', myth:true,
      grip:-2, end:S=>S.rescue>=S.goal?'e_trail_found':null, go:'t_lastcall' },
  ]},
t_lastcall:{ region:'offtrail', title:'The Long Game',
  text:S=>`Another night, then. The rations of the situation get thinner: less food, less charge, less of the elastic in your legs — but the arithmetic of search-and-rescue gets <em>fatter</em> every hour. More people. Wider grid. Your name on more radios. The overdue hiker does not get forgotten; the overdue hiker gets escalated.\n\n${S.v.grip>=2&&S.v.body>=2?`And there is the other door, the one your legs keep looking at: ${S.flags.treeview?'from the tree you saw the dome, and from the dome the land fell west —':'west, where the road has to be —'} a deliberate, marked, daylight walk-out. Not a panic. A plan. It would cost everything you have left, and it might spend it on nothing.`:'Walking out is no longer on the menu — your body has quietly taken it off. There is one strategy left, and it is the one that was always best: be here, be loud, be visible, and last.'}`,
  choices:[
    { t:'Hold the ground. Feed the smoke, square the X, whistle the threes. Make tomorrow’s square be this one.',
      pre:'the found ones stayed', day:1, rescue:1, water:-1, food:-1, go:'t_search' },
    { t:'The deliberate walk-out: west, marking every fifty yards, sun on your left shoulder, no drainages, no shortcuts.',
      pre:'a plan is not a panic', req:S=>S.v.grip>=2&&S.v.body>=2,
      end:S=>(S.v.warmth>=2&&S.v.water>=2)?'e_trail_walkout':'e_trail_cold' },
    { t:'Sit against the slab and let the fire go where fires go.', grip:-2, go:'t_lastcall' },
  ]},

};

/* ======================================================================
   ENDINGS
   ====================================================================== */
const endings = {
  /* ---- WHITE ---- */
  e_white_cold:{ kind:'death', art:'whiteout', scen:'white', title:'The Cold Took the Argument',
    text:`They find you in the thaw, weeks later, and the strange gentle mercy of hypothermia is that the end of it doesn’t feel like cold at all. It feels like warmth, and then like sleep. The country simply subtracted you, one degree at a time, the way it does with everything that stops feeding its fire.` },
  e_white_thirst:{ kind:'death', art:'whiteout', scen:'white', title:'Dry in a World of Ice',
    text:`Surrounded by frozen water, you never drank enough of it — melting snow costs heat you couldn’t spare, and you rationed the wrong resource. Dehydration thickened your blood and clouded your judgment until the last few decisions were made by someone who was no longer quite you.` },
  e_white_starve:{ kind:'death', art:'whiteout', scen:'white', title:'The Long Clock Ran Out',
    text:`Food is the slow clock — three weeks, they say — but it doesn’t wait that long to beat you. It takes your strength and your warmth and your will first, hollows you out, and lets the cold finish a body too weak to shiver. You lasted a long time. Not quite long enough.` },
  e_white_bleed:{ kind:'death', art:'whiteout', scen:'white', title:'First Rule, Broken',
    text:`Stop the bleeding first — it is the first rule because everything else is meaningless without it. The wound you didn’t tend, or the fall you took, spent the one resource you can’t ration or find more of. The snow around you is very white and then, slowly, it isn’t.` },
  e_white_giveup:{ kind:'death', art:'gone', scen:'white', title:'You Sat Down',
    text:`Your body could have gone further. It was your mind that stopped — the small quiet voice that decided the next stick, the next hour, the next anything, simply wasn’t worth it. That voice kills more people out here than the temperature ever does. You sat down in the snow, and the snow was patient, and that was all.` },
  e_white_drown:{ kind:'death', art:'deepsea', scen:'white', title:'The Ice Was Lying',
    text:`The river looked like a road and the ice looked like ground and both of them lied. Cold water steals heat thirty times faster than cold air; you had minutes and you spent them in the current. Downstream really was the way out. Just not on the ice, and not like this.` },
  e_white_saved:{ kind:'survive', art:'ridge', scen:'white', real:'koepcke', title:'They Came For the Wreck',
    text:`The Otter’s wing dips — once, sharply, deliberately — <em>we see you.</em> You stay with the wreck, you built the fire and held the mirror, and you made yourself into something a searching eye could not slide past. An hour later there are hands on you, and a thermos, and a voice saying your name like it’s good news. Because you stayed put, and stayed alive, and let them do their job.` },
  e_white_walkout:{ kind:'survive', art:'forest', scen:'white', real:'koepcke', title:'Downstream Was Out',
    text:`The chainsaw was real. You come out of the timber into a logging cut and a man drops his saw and just stares at the thing walking toward him out of the country that eats people. You followed the water down, the way Juliane Koepcke did, one careful dry step at a time, and the water kept its ancient promise: it led you home.` },
  /* ---- RAFT ---- */
  e_raft_heat:{ kind:'death', art:'baked', scen:'raft', title:'The Sun Won',
    text:`Out here the sun is the cold’s twin — it kills just as surely, from the other direction. Without shade you cooked, hour after hour, your water boiling out through your skin faster than any still could replace. Heatstroke stops the heart as cleanly as any blizzard. The sea took its time, and then it didn’t.` },
  e_raft_thirst:{ kind:'death', art:'baked', scen:'raft', title:'You Drank the Sea',
    text:`The oldest, best-marked trap on the ocean, and you walked into it: the seawater made you thirstier, and the thirst made you drink more, and the salt drove you mad by degrees before it finished the arithmetic. You died of thirst in the middle of all that undrinkable water — which is exactly, precisely why every manual screams not to.` },
  e_raft_starve:{ kind:'death', art:'open', scen:'raft', title:'The Garden Went Untended',
    text:`The sea was trying to feed you — dorado in the shade, barnacles on the hull — and you couldn’t or wouldn’t take it. Starvation is patient and total. It emptied you out over long bright days until there was nothing left to keep the small fires of a body burning.` },
  e_raft_bleed:{ kind:'death', art:'deepsea', scen:'raft', title:'Blood in the Water',
    text:`You gave the sea something to hunt, and the sea is very good at hunting. The grey shape came back for what you offered it. Out here a wound is not just a wound — it is a signal, broadcast into the water, and the ocean answers signals like that with terrible speed.` },
  e_raft_giveup:{ kind:'death', art:'gone', scen:'raft', title:'You Stopped Bailing',
    text:`The ship passing was the wound; giving up was the death. You stopped tending the still, stopped fishing, stopped writing it down, stopped doing the small stupid saving chores — and a raft that isn’t tended is just a slower way to drown. On the sea as everywhere, it’s the mind that taps out first.` },
  e_raft_shark:{ kind:'death', art:'deepsea', scen:'raft', title:'You Left the Raft',
    text:`The raft was not prey and neither were you, as long as you stayed in it. The moment you swam — for the smudge, for the ship, for the fish — you became a small warm thrashing thing in a very large ocean, and the ocean is full of things that have waited their whole lives for exactly that.` },
  e_raft_saved:{ kind:'survive', art:'open', scen:'raft', real:'callahan', title:'The Birds Brought Them',
    text:`Rough hands haul you over a gunwale and you weigh nothing, a bundle of salt sores and sunburn and stubbornness. The fishermen followed the birds, and the birds followed the little ecosystem you carried across an ocean, and so the life you couldn’t stop cultivating under your raft reached up and saved you. Seventy-odd days. You did the small things, every day, and the small things carried you home.` },
  e_raft_land:{ kind:'survive', art:'open', scen:'raft', real:'callahan', title:'A Line of Green',
    text:`It resolves out of the haze and refuses to dissolve: land. Real, solid, growing land, and the current that carried you for weeks is setting you gently onto it. You paddle the last of it with hands that barely close, and you crawl up a beach on all fours, and you press your face into sand that does not move like water, and you are, impossibly, still breathing.` },
  /* ---- PINCH ---- */
  e_pinch_cold:{ kind:'death', art:'slotnight', scen:'pinch', title:'The Canyon Kept You',
    text:`It wasn’t the heat and it wasn’t even the thirst in the end — it was one of the long cold nights, your pinned body unable to move enough to make its own warmth, shivering out the last of a fuel tank that dehydration had already drained. The desert is colder than anyone believes until it has them.` },
  e_pinch_thirst:{ kind:'death', art:'baked', scen:'pinch', title:'The Bottle, and Then Nothing',
    text:`Three days without water, they say, and the canyon held you longer than that. Rationed to the last, then your own body’s return, then nothing — and dehydration doesn’t just dry you out, it fogs the mind that might have found the way out, until the one terrible saving idea can’t form anymore. It was there. You just couldn’t reach it in time.` },
  e_pinch_bleed:{ kind:'death', art:'slot', scen:'pinch', title:'By Force',
    text:`You tried to tear yourself free by strength, or the rock took more than it was ever going to give back gently. The body has only so much blood and the canyon floor drank it. There was a way through this — a deliberate, controlled, unthinkable way — and force was never it.` },
  e_pinch_giveup:{ kind:'death', art:'gone', scen:'pinch', title:'Twenty Feet From Your Own Legs',
    text:`Your legs were fine. That is the unbearable part. Below the pinned arm you were whole and strong and one impossible decision away from walking out — and the decision was too big, and you set it down, and you closed your eyes against the cool rock. The body doesn’t give up here. Only the mind does. Only ever the mind.` },
  e_pinch_cut:{ kind:'survive', art:'canyonout', scen:'pinch', real:'ralston', title:'The Way Out Is Through',
    text:`The bones go with a sound you will hear for the rest of your life. Then the tourniquet, and then the dull little blade, and then a length of time that your mind mercifully refuses to store properly — and then you are <em>free</em>, reeling, one-armed, alive.\n\nYou rappel the drop. You walk. Seven miles of desert on the strength of a hallucinated child and a decision you made against every instinct you own. And when the other hikers come around the bend and freeze at the sight of you, you are already, somehow, the luckiest person any of them will ever meet — because you chose the door, and you walked through it, and it led to the rest of your life.` },
  /* ---- TRAIL ---- */
  e_trail_cold:{ kind:'death', art:'faded', scen:'trail', title:'Forty-Five Degrees',
    text:`Not a blizzard. Not an ice storm. A night of steady rain in the mid-forties — weather a parking lot would call "chilly" — and wet cotton, and moving air, and a body that spent its last fuel shivering somewhere past midnight and then, quietly, stopped.\n\nHikers have died of exactly this, in summer, two miles from a marked trail, while their families assumed the mountains must at least have had the decency to be dramatic about it. The forties don’t need drama. They just need you wet, and time.` },
  e_trail_thirst:{ kind:'death', art:'gone', scen:'trail', title:'Clear Water, Untouched',
    text:`You knelt over running water and wouldn’t drink it, because a pamphlet once told you about a parasite that causes a bad month. Dehydration causes a bad forever, and it works faster — it thickened your blood, fogged the exact judgment you needed for every other decision, and handed the forest a slower, stupider version of you to finish.\n\nGiardia is treatable at a clinic in three weeks. There was never going to be a clinic if there wasn’t a you.` },
  e_trail_starve:{ kind:'death', art:'faded', scen:'trail', title:'The Long Fade',
    text:`Food is the slow clock, and out here it never got the chance to run out honestly — it just kept lending its minutes to the other clocks. Too hollow to gather wood. Too hollow to whistle on schedule. Too hollow, finally, to keep the signals squared to the sky.\n\nThe camp was still there when they found it. It had simply stopped being tended, the way a candle doesn’t decide to go out.` },
  e_trail_fall:{ kind:'death', art:'creekbed', scen:'trail', title:'The Drain',
    text:`Search-and-rescue teams have a grim shorthand: when someone stays lost too long, <em>check the drainages</em>. Water pulls people the way it pulls everything — downhill, into the steep and the slick and the choked, where the walls climb and the helicopters can’t see and one wet boulder ends the argument.\n\nThe creek was never a path. It was a drain, and things that go down a drain do not come back up it.` },
  e_trail_giveup:{ kind:'death', art:'gone', scen:'trail', title:'Twenty Minutes From the Junction',
    text:`They find you eventually, because they always do — that is the bitter mercy of a national park. And the debrief will contain a sentence no one reads aloud twice: the site was approximately twenty minutes’ walk from a maintained trail junction.\n\nYou weren’t twenty minutes from surviving. You were twenty minutes from a bench with a map on it. The forest didn’t take you. You sat down against a log inside the sound of a place people picnic, and agreed to stop.` },
  e_trail_found:{ kind:'survive', art:'meadow', scen:'trail', real:'eller', title:'The Square With the X In It',
    text:S=>`The winch operator will tell you later that from four hundred feet, the forest is a single unbroken thing — except for one meadow with an orange X squared to the sky, a smudge of deliberate smoke, and a person standing dead-center making a Y of themselves. "Like a signature," he’ll say. "Like the forest signed you."\n\n${S.days} day${S.days>1?'s':''} overdue, and every unglamorous hour of it — the stopping, the staying, the whistle-threes, the tarp re-staked in the rain — turned out to be you, writing your name where the sky could read it.` },
  e_trail_walkout:{ kind:'survive', art:'trailday', scen:'trail', real:'eller', title:'The Deliberate Line',
    text:`West, marked every fifty yards, sun held on your left shoulder like a hand — not the panicked stumble that got you lost, but its exact opposite: a plan, walked slowly, by someone who had already survived the worst of themselves.\n\nAnd then the ground does something ground hasn’t done in days: it flattens into a made thing. Crushed granite. An edge. A trail — with a couple coming up it in clean shirts, who stop dead, because the forest just handed them a person made of scratches and rain.\n\nYou sit down in the middle of the path. It’s the softest thing you’ve ever felt.` },
  /* ---- META ---- */
  e_stillbreathing:{ kind:'true', art:'dawn', real:'mind', title:'Still Breathing',
    text:`Every ordeal. Every way the world tried to subtract you — cold, thirst, a rock that wouldn’t let go, a forest that deleted the path home — and every time, you came back.\n\nHere is the secret they all share, the one the survivors always tell afterward, almost apologetically, because it sounds too simple to be the answer: <em>you didn’t panic. You did the next small thing. You accepted where you actually were instead of where you wished you were. And you held onto a reason — a person, a promise, a future — that the cold and the salt and the stone could not reach.</em>\n\nThe body can go astonishingly far. It is nearly always the mind that decides. You kept yours. Whatever comes for you next — and something always comes — you know now what you’re made of.\n\nYou’re still breathing. That was always the only thing you had to keep doing.` },
};

return { scenarios, regions, items, logs, reals, endings, nodes, helpers, loadout };
})();
